# Generated by Django 5.0.6 on 2024-07-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
