# Generated by Django 5.0.6 on 2024-07-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_app', '0002_alter_csvfile_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
