# Generated by Django 5.0.6 on 2024-07-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_app', '0003_datarecord_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='value',
        ),
        migrations.AlterField(
            model_name='datarecord',
            name='json_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
